apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "fumy/data/man-api-staging" #path of secret in vault
type: Opaque
stringData:
  sample-secret: <password> #Fomat should be like this with key
